#!/usr/bin/env python3
"""
Soft elimination -- a likelihood layer, so one off-policy human move does not
destroy the hypothesis set.

WHY THIS BLOCKS THE HUMAN PILOT. Exact elimination assumes the subject is inside
the model. Our own 20-hand pilot scored soundness 9/20: over half of one real
person's hands produced behaviour that no intent explained, with no deception
involved at all. Under hard elimination a single move off the declared policy
either removes the true intent or empties the set entirely. Human data scored
that way measures the subject's sloppiness, not the observer's capability.

THE MODEL. Each subject decision is generated by the declared policy with
probability (1 - eps), and uniformly at random over the legal actions with
probability eps:

    P(a | intent, card, node) = (1 - eps) * [policy(intent, card, node) == a]
                              + eps / |legal(node)|

The hypothesis set becomes a posterior over intents under a uniform prior, with
the unseen card PROFILED OUT (max, not sum) -- because hard elimination asks
"is there SOME card under which this intent explains what we saw", which is an
existential. Card facts stay HARD: the observer's own card is impossible, and a
card revealed at showdown is observed, not inferred. Only *behaviour* is noisy.

METRIC DEFINITIONS, AND WHY THEY COLLAPSE AT eps = 0. At eps = 0 every
consistent hypothesis has likelihood 1 and every inconsistent one has 0, so the
posterior is UNIFORM over exactly the hard-elimination survivors. Each metric
below is chosen so that it then reduces to the committed one exactly:

  |H| eff   exp(Shannon entropy of the intent posterior), i.e. perplexity.
            Uniform over k intents -> exp(ln k) = k. Identical to |H| final.

  exact ID  MAP intent is the declared one AND carries mass >= TAU (0.9).
            Uniform over k -> mass 1/k, so mass >= 0.9 iff k == 1. Identical.

  misID     MAP intent carries mass >= TAU and is NOT the declared one.
            Same argument. Identical.

  sound     declared intent is inside the 95% highest-posterior-density set.
            Uniform over k -> the HPD set is all k, so this is "declared
            survived". Identical.

  contra    no intent explains the behaviour WITHOUT invoking noise -- i.e. the
            hard support is empty. This is the one metric that keeps its hard
            definition at every eps, on purpose: "the model is refuted unless we
            allow the subject to have slipped" is exactly the quantity we want,
            and at eps > 0 nothing is ever strictly impossible, so a posterior
            version of it would be vacuous.

TAU and the HPD level are reported with every table; they are the only free
parameters and neither affects the eps = 0 case.

    python3 soft.py --verify          # eps=0 reproduces every committed metric
    python3 soft.py --sweep           # degradation as the subject gets noisier
    python3 soft.py --pilot pilot.json
"""

import argparse
import json
import math
import random

import kuhn_intent as K
import leduc_intent as L

TAU = 0.9          # mass the MAP intent must carry to count as an identification
HPD = 0.95         # credible level for soundness


# ------------------------------------------------------------- the posterior

def _subject_nodes(mod, history):
    """(prefix, action, n_legal) for every decision the SUBJECT made."""
    out, prefix = [], ()
    for t in history:
        if not str(t).startswith("board:") and mod.to_act(prefix) == "subject":
            out.append((prefix, t, len(mod.legal(prefix))))
        prefix += (t,)
    return out


def posterior(mod, history, observer_card, revealed_card, eps):
    """Posterior over intents given one episode. Uniform prior over (intent, card);
    card facts hard, behaviour soft."""
    cards = [c for c in mod.DECK if c != observer_card] if hasattr(mod, "DECK") \
        else [c for c in mod.CARDS if c != observer_card]
    board = mod.board_of(history) if hasattr(mod, "board_of") else None
    if board:
        cards = [c for c in cards if c != board]
    if revealed_card is not None:
        cards = [c for c in cards if c == revealed_card]

    # PROFILE, not marginalise, over the card. Hard elimination asks "is there
    # SOME card under which this intent explains what we saw" -- an existential,
    # i.e. a maximum over the nuisance variable. Summing instead would weight an
    # intent by how MANY cards happen to fit it, and then the eps = 0 posterior
    # is not uniform over the survivors and |H| eff no longer collapses to
    # |H| final. (Measured: summing broke 1511 of 5400 episodes on that metric
    # alone. The falsifier caught the wrong choice.)
    nodes = _subject_nodes(mod, history)
    w = {}
    for i in mod.INTENTS:
        m = 0.0
        for c in cards:
            lik = 1.0
            for prefix, a, nlegal in nodes:
                p = eps / nlegal
                if _policy(mod, i, c, prefix) == a:
                    p += 1.0 - eps
                lik *= p
            m = max(m, lik)
        w[i] = m
    tot = sum(w.values())
    if tot <= 0:
        return {}, cards            # nothing at all explains it, even with noise
    return {i: v / tot for i, v in w.items() if v > 0}, cards


def _policy(mod, intent, card, prefix):
    return mod.policy(intent, card, prefix) if hasattr(mod, "policy") \
        else mod.subject_policy(intent, card, prefix)


def hard_support(mod, history, observer_card, revealed_card):
    """The eps = 0 survivor set -- used for the contradiction metric at every eps."""
    p, _ = posterior(mod, history, observer_card, revealed_card, 0.0)
    return sorted(p)


# ---------------------------------------------------------------- metrics

def eff_size(p):
    """Perplexity of the intent posterior. Uniform over k gives exactly k."""
    if not p:
        return 0.0
    h = -sum(v * math.log(v) for v in p.values() if v > 0)
    return math.exp(h)


def hpd_set(p, level=HPD):
    out, acc = [], 0.0
    for i, v in sorted(p.items(), key=lambda kv: -kv[1]):
        out.append(i)
        acc += v
        if acc >= level - 1e-12:
            break
    return out


def score_episode(mod, history, observer_card, revealed_card, declared, eps,
                  tau=TAU, level=HPD):
    p, _ = posterior(mod, history, observer_card, revealed_card, eps)
    hard = hard_support(mod, history, observer_card, revealed_card)
    if not p:
        return {"exact": False, "H": 0.0, "sound": False, "misID": False,
                "contra": True, "map_mass": 0.0}
    m_int, m_mass = max(p.items(), key=lambda kv: kv[1])
    return {
        "exact": m_int == declared and m_mass >= tau,
        "H": eff_size(p),
        "sound": declared in hpd_set(p, level),
        "misID": m_mass >= tau and m_int != declared,
        "contra": len(hard) == 0,
        "map_mass": m_mass,
    }


# -------------------------------------------------------- record extraction

def episode_fields(mod, rec):
    """(history, observer_card, revealed_card, declared) from a logged record.
    Handles Leduc records (which carry `history`) and Kuhn records (which carry
    a `trace`, including the older pilot format)."""
    if "history" in rec:
        hist = tuple(rec["history"])
    else:
        hist = tuple(t["action"] for t in rec["trace"] if t["who"] in ("subject", "observer"))
    revealed = rec["subject_card"] if rec.get("card_revealed",
                                              mod.is_showdown(hist) if hist else False) else None
    return hist, rec["observer_card"], revealed, rec["declared"]


# ------------------------------------------------------------------ actions

def verify(hands=400, seeds=(1, 2, 3)):
    """eps = 0 must reproduce every committed metric, cell for cell."""
    print("\n## eps = 0 reproduces hard elimination\n")
    print("Every metric recomputed through the likelihood layer at eps = 0 and")
    print("compared to the value the hard-elimination run recorded, per episode.\n")
    total = bad = 0
    detail = {}
    for mod, name, kw in ((K, "kuhn", {"observer": "lookahead"}), (L, "leduc", {})):
        for cond in ["passive", "random", "adaptive"]:
            for subj in (["faithful", "misfit"] if mod is K else
                         ["faithful", "misfit:in_model", "misfit:out_of_model"]):
                for s in seeds:
                    rng, orng = random.Random(s), random.Random(s + 10 ** 6)
                    rows = [mod.play_hand(cond, rng, hand_no=k + 1, subject=subj,
                                          orng=orng, **kw) for k in range(hands)]
                    for r in rows:
                        hist, oc, rev, decl = episode_fields(mod, r)
                        got = score_episode(mod, hist, oc, rev, decl, 0.0)
                        want = {"exact": r["exact"], "H": float(r["final_size"]),
                                "sound": r["sound"], "misID": r["misattributed"],
                                "contra": r.get("contradiction", False)}
                        total += 1
                        for k2, v in want.items():
                            if (abs(got[k2] - v) > 1e-9 if k2 == "H" else got[k2] != v):
                                bad += 1
                                detail.setdefault((name, cond, subj, k2), 0)
                                detail[(name, cond, subj, k2)] += 1
                                break
    print(f"  episodes checked: {total}")
    print(f"  episodes where ANY metric differs: {bad}")
    for k, v in sorted(detail.items())[:10]:
        print(f"    {k}: {v}")
    print("\n  " + ("PASS -- the likelihood layer is a strict generalisation."
                    if bad == 0 else "FAIL -- eps=0 does not reproduce the baseline."))
    return bad == 0


EPS_GRID = [0.0, 0.02, 0.05, 0.1, 0.2, 0.35, 0.5]


def sweep(hands=1000, seeds=(1, 2, 3)):
    """How the result degrades as the subject gets noisier.

    The subject really does slip: with probability eps_true it takes a uniformly
    random legal action instead of its declared one. The observer scores with
    eps_model. The diagonal (matched) is the honest case; the eps_model = 0
    column shows what hard elimination does to the same behaviour."""
    print("\n## Noisy subject: what soft elimination buys\n")
    print(f"tau = {TAU} (mass the MAP intent must carry), HPD level = {HPD}")
    print(f"n = {hands} hands x {len(seeds)} seeds = {hands * len(seeds)} per cell, "
          f"Leduc, adaptive observer, faithful intent.\n")
    hdr = (f"{'eps_true':>9} | {'scored eps=0 (hard)':^38} | {'scored eps=eps_true (matched)':^38}")
    print(hdr)
    print(f"{'':>9} | {'exact':>8}{'|H|eff':>9}{'sound':>9}{'contra':>10} | "
          f"{'exact':>8}{'|H|eff':>9}{'sound':>9}{'contra':>10}")
    print("-" * len(hdr))
    for et in EPS_GRID:
        acc = {0: [], 1: []}
        for s in seeds:
            rng, orng = random.Random(s), random.Random(s + 10 ** 6)
            nz = random.Random(s + 99)
            rows = []
            for k in range(hands):
                r = L.play_hand("adaptive", rng, hand_no=k + 1, subject="faithful", orng=orng)
                rows.append(r)
            # Re-generate the subject's moves with slips, replaying the same deal.
            for r in rows:
                hist, oc, rev, decl = episode_fields(L, r)
                hist = _noisy_replay(L, r, et, nz)
                rev2 = r["subject_card"] if L.is_showdown(hist) else None
                for j, em in enumerate([0.0, et]):
                    acc[j].append(score_episode(L, hist, oc, rev2, decl, em))
        def mean(rs, k):
            return sum(x[k] for x in rs) / len(rs)
        print(f"{et:>9.2f} | {mean(acc[0],'exact'):>7.1%}{mean(acc[0],'H'):>9.2f}"
              f"{mean(acc[0],'sound'):>9.1%}{mean(acc[0],'contra'):>10.1%} | "
              f"{mean(acc[1],'exact'):>7.1%}{mean(acc[1],'H'):>9.2f}"
              f"{mean(acc[1],'sound'):>9.1%}{mean(acc[1],'contra'):>10.1%}")


def _noisy_replay(mod, rec, eps_true, rng):
    """Replay the deal with the subject slipping at rate eps_true."""
    sc, oc = rec["subject_card"], rec["observer_card"]
    board = rec["board_card"]        # the dealt board, whether or not it was reached
    declared = rec["declared"]
    hist, H = (), mod.initial_hypotheses(oc)
    while mod.to_act(hist) != "terminal":
        who = mod.to_act(hist)
        if who == "chance":
            hist += ("board:" + board,)
            H = tuple((i, c) for (i, c) in H if c != board)
            continue
        if who == "subject":
            legal = mod.legal(hist)
            a = rng.choice(legal) if rng.random() < eps_true else mod.policy(declared, sc, hist)
        else:
            a = mod.choose_observer_action(H, hist, oc, "adaptive", rng, 0.0)
            hist += (a,)
            continue
        H = tuple((i, c) for (i, c) in H if mod.policy(i, c, hist) == a)
        hist += (a,)
    return hist


def rescore_pilot(path):
    """How much of the pilot's 9/20 soundness was genuine misfit, and how much
    was the model being brittle?"""
    recs = json.load(open(path))
    print(f"\n## Re-scoring {path} -- {len(recs)} real human hands (Kuhn)\n")
    print("The same 20 hands, scored at several eps. Only the SCORING changes;")
    print("the behaviour is fixed human data.\n")
    print(f"{'eps':>6}{'sound':>9}{'exact':>9}{'|H| eff':>10}{'contra':>9}"
          f"{'mean mass on declared':>24}")
    print("-" * 67)
    for eps in [0.0, 0.05, 0.1, 0.2, 0.35, 0.5]:
        agg = {"sound": 0, "exact": 0, "H": 0.0, "contra": 0, "mass": 0.0}
        for r in recs:
            hist, oc, rev, decl = episode_fields(K, r)
            sc = score_episode(K, hist, oc, rev, decl, eps)
            p, _ = posterior(K, hist, oc, rev, eps)
            agg["sound"] += sc["sound"]; agg["exact"] += sc["exact"]
            agg["H"] += sc["H"]; agg["contra"] += sc["contra"]
            agg["mass"] += p.get(decl, 0.0)
        n = len(recs)
        print(f"{eps:>6.2f}{agg['sound']/n:>9.1%}{agg['exact']/n:>9.1%}"
              f"{agg['H']/n:>10.2f}{agg['contra']/n:>9.1%}{agg['mass']/n:>24.3f}")
    print("\n  'mean mass on declared' is the honest headline: how much posterior")
    print("  weight the intent the person actually stated still carries at the end.")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--verify", action="store_true")
    ap.add_argument("--sweep", action="store_true")
    ap.add_argument("--pilot", metavar="PATH")
    ap.add_argument("--hands", type=int, default=400)
    a = ap.parse_args()
    if a.verify or not (a.sweep or a.pilot):
        verify(a.hands)
    if a.sweep:
        sweep()
    if a.pilot:
        rescore_pilot(a.pilot)


if __name__ == "__main__":
    main()
